lib/hello_web/router.ex
defmodule HelloWeb.Router do
  use HelloWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {HelloWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HelloWeb.Plugs.Locale, "en"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelloWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/transaction", TransactionController, :index
    post "/transaction/result", TransactionController, :result
  end

  # Other scopes may use custom stacks.
  # scope "/api", HelloWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: HelloWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/hello/application.ex
defmodule Hello.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Telemetry supervisor
      HelloWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Hello.PubSub},
      # Start the Endpoint (http/https)
      HelloWeb.Endpoint
      # Start a worker by calling: Hello.Worker.start_link(arg)
      # {Hello.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Hello.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    HelloWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/hello/mailer.ex
defmodule Hello.Mailer do
  use Swoosh.Mailer, otp_app: :hello
end

lib/hello_web/controllers/page_controller.ex
defmodule HelloWeb.PageController do
  use HelloWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/hello_web/controllers/transaction_controller.ex
defmodule HelloWeb.TransactionController do
  use HelloWeb, :controller

  def index(conn, _params) do
    conn
    |> render("index.html", csrf: csrf_token(conn), result_is_present: false)
  end

  def result(conn, %{"form_data" => %{"tx_hash" => hash}}) do
    txhash = hash
    apikey = Application.fetch_env!(:transaction_config, :etherscan_api_key)
    url = "https://api.etherscan.io/api?module=transaction&action=getstatus&txhash=#{txhash}&apikey=#{apikey}"
    headers = []
    params = []
    %{body: body} = HTTPoison.get! url , headers, params: params
    %{result: %{isError: is_error}} = Poison.decode! body, keys: :atoms
    conn
    |> render("index.html", hash: hash, is_error: is_error, result_is_present: true)
  end

  def csrf_token(conn) do
    Plug.Conn.get_session(conn, :csrf_token)
  end

end

lib/hello_web/views/error_view.ex
defmodule HelloWeb.ErrorView do
  use HelloWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/hello_web/views/layout_view.ex
defmodule HelloWeb.LayoutView do
  use HelloWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/hello_web/views/page_view.ex
defmodule HelloWeb.PageView do
  use HelloWeb, :view
end

lib/hello_web/views/transaction_view.ex
defmodule HelloWeb.TransactionView do
  use HelloWeb, :view
end

lib/hello_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/hello_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/hello_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Hello", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/hello_web/templates/page/index.html.heex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}", name: "Transaction-Validator 800" %></h1>
  <h2>(T-800)</h2>
  <p>Click on the start button to begin validating your transactions</p>
  <%= button("start", to: "/transaction/", method: "get", class: "btn") %>
</section>

lib/hello_web/templates/transaction/index.html.heex
<section class="phx-hero">
  <%= if @result_is_present do %>
    <p>Your tx hash is</p>
    <p><%= @hash %></p>
    <%= if @is_error == "1" do %>
      <p>
        <img src="/images/red-error.png" style="max-width: 4%; vertical-align: middle;"/>
        Unfortunatelly the transaction has been reverted
      </p>
    <% else %>
      <p>
        <img src="/images/green-check.png" style="max-width: 4%; vertical-align: middle;"/>
        Great! your transaction has made it through :)
      </p>
    <% end %>
  <% end %>

  <h2>Enter a transaction hash and check if is valid</h2>
  <%= form_for @conn, Routes.transaction_path(@conn, :result), [as: :form_data], fn f -> %>
    <%= text_input f, :tx_hash %>
    <%= submit "Search" %>
  <% end %>
</section>

lib/hello_web/templates/transaction/result.html.heex
<section class="phx-hero">
  <%= if @result_is_present do %>
    <h2>This is Result: <%= @hash %></h2>
    <%= if @is_error == "1" do %>
      <p>Is error</p>
    <% else %>
      <p>All good</p>
    <% end %>
  <% end %>

  <h2>Que onda lo perrooooo!</h2>
  <%= form_for @conn, Routes.transaction_path(@conn, :result), [as: :form_data], fn f -> %>
    <%= text_input f, :tx_hash %>
    <%= submit "Search" %>
  <% end %>
</section>

lib/hello_web/templates/transaction/show.html.heex
<section class="phx-hero">
  <h2>Hola <%= @messenger %>, puto de mierda!</h2>
</section>